language: node_js

node_js:
  - "9"
  - "8"

before_install:
  - curl -L https://unpkg.com/@pnpm/self-installer | node
install:
  - pnpm install

# https://docs.travis-ci.com/user/docker/
sudo: required
services:
  - docker

script:
  - npm run lint-ci
  - docker-compose up -d dynamodb && npm run test-ci
  - docker-compose down

notifications:
  email:
    on_success: never
    on_failure: always
